version: '2.1'
networks:
  backing-services:
    driver: bridge
services:
  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    ports: ['5432:5432']
    networks: [backing-services]
